import {useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {webSupabaseClient} from '../backend/supabase/runtime';
import './operationalDirectory.css';
export type DirectoryEntry={id:string;kind:'WORKER'|'MACHINE';code:string;name:string;job:string;machine_type:string;identifier:string;meter_unit:''|'h'|'km';fuel:''|'ACPM'|'Gasolina';active:boolean;revision:number};
const empty=(kind:DirectoryEntry['kind']):DirectoryEntry=>({id:crypto.randomUUID(),kind,code:'',name:'',job:'',machine_type:'',identifier:'',meter_unit:'',fuel:'',active:true,revision:0});
export default function OperationalDirectory(){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<DirectoryEntry[]>([]),[kind,setKind]=useState<DirectoryEntry['kind']>('WORKER'),[search,setSearch]=useState(''),[draft,setDraft]=useState<DirectoryEntry|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),request=useRef<{key:string;id:string}|null>(null);
 useEffect(()=>{if(open){dialog.current?.showModal();void load();}else dialog.current?.close();},[open]);
 async function load(){setBusy(true);setError('');try{const {data,error}=await webSupabaseClient().rpc('operational_directory_list');if(error||!Array.isArray(data))throw Error();setRows(data);}catch{setError('No se pudo cargar el catálogo. Reintenta con Actualizar.');}finally{setBusy(false);}}
 async function save(item:DirectoryEntry){setBusy(true);setError('');const key=JSON.stringify(item);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};try{const {data,error}=await webSupabaseClient().rpc('operational_directory_save',{p_request_id:request.current.id,p_id:item.id,p_expected_revision:item.revision,p_data:item});if(error)throw error;setRows(old=>[...old.filter(r=>r.id!==item.id),data].sort((a,b)=>a.name.localeCompare(b.name)));setDraft(null);request.current=null;}catch{setError('No se pudo guardar. Verifica nombres/códigos duplicados o actualiza si otro administrador editó el registro.');}finally{setBusy(false);}}
 const field=(key:keyof DirectoryEntry,value:string)=>setDraft(d=>d?{...d,[key]:value}:d);
 return <><button type="button" className="pending-users-button" onClick={()=>setOpen(true)}>Trabajadores y maquinarias</button>{open&&createPortal(<dialog className="operational-directory" ref={dialog} onCancel={e=>{e.preventDefault();if(!busy)setOpen(false);}}><header><h2>Trabajadores y maquinarias</h2><button disabled={busy} aria-label="Cerrar catálogo" onClick={()=>setOpen(false)}>Cerrar</button></header><p>Catálogo compartido por Almacén y Taller. Retirar oculta la opción en los celulares al actualizar; conserva el historial y permite reactivar.</p><nav>{(['WORKER','MACHINE'] as const).map(k=><button key={k} disabled={busy} aria-pressed={kind===k} onClick={()=>{setKind(k);setDraft(null);}}>{k==='WORKER'?'Trabajadores':'Maquinarias'}</button>)}<button disabled={busy} onClick={()=>void load()}>Actualizar</button><button disabled={busy} onClick={()=>setDraft(empty(kind))}>Añadir {kind==='WORKER'?'trabajador':'maquinaria'}</button></nav>{error&&<p role="alert">{error}</p>}
 {draft?<form onSubmit={e=>{e.preventDefault();void save(draft);}}><h3>{draft.revision?'Editar':'Añadir'} {kind==='WORKER'?'trabajador':'maquinaria'}</h3><label>Código único<input required maxLength={40} pattern="[A-Za-z0-9_-]+" disabled={busy||draft.revision>0} value={draft.code} onChange={e=>field('code',e.target.value.toUpperCase())}/></label><label>Nombre completo<input required maxLength={120} disabled={busy} value={draft.name} onChange={e=>field('name',e.target.value)}/></label>
 {kind==='WORKER'?<label>Cargo<input required maxLength={120} disabled={busy} value={draft.job} onChange={e=>field('job',e.target.value)}/></label>:<><label>Tipo<select required disabled={busy} value={draft.machine_type} onChange={e=>field('machine_type',e.target.value)}><option value="">Selecciona</option>{['Tractor','Moto','Camioneta','Planta','Otro'].map(t=><option key={t}>{t}</option>)}</select></label><label>Identificación / placa / color<input required maxLength={40} disabled={busy} value={draft.identifier} onChange={e=>field('identifier',e.target.value)}/></label><label>Contador<select disabled={busy} value={draft.meter_unit} onChange={e=>field('meter_unit',e.target.value)}><option value="">Sin contador</option><option value="h">Horómetro (horas)</option><option value="km">Kilometraje</option></select></label><label>Combustible<select disabled={busy} value={draft.fuel} onChange={e=>field('fuel',e.target.value)}><option value="">No aplica</option><option>ACPM</option><option>Gasolina</option></select></label></>}
 <button disabled={busy}>Guardar</button><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</button></form>:<><label>Buscar<input value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="directory-list">{rows.filter(r=>r.kind===kind&&`${r.code} ${r.name} ${r.job} ${r.identifier}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(r=><article key={r.id}><div><strong>{r.name}</strong><p>{r.code} · {r.kind==='WORKER'?r.job:`${r.machine_type} · ${r.identifier} · ${r.meter_unit||'Sin contador'} · ${r.fuel||'No aplica'}`}</p><small>{r.active?'Activo':'Retirado'}</small></div><button disabled={busy} onClick={()=>setDraft(r)}>Editar</button><button disabled={busy} onClick={()=>void save({...r,active:!r.active})}>{r.active?'Retirar':'Reactivar'}</button></article>)}</div>{!rows.some(r=>r.kind===kind)&&<p>Aún no hay registros. Añade los nombres y cargos confirmados.</p>}</>}
 </dialog>,document.body)}</>;
}
